### ISSUE TITLE
Choice tags component inaccessible from global scope

### ISSUE THREAD

**Issue by icecaster** [CodyHouse/cd-choice-tags-changelog#1]
Hey there

would be helpful to have access to the choicetags class from a global scope to initialise dynamically created elements.

a simple 
`
window.ChoiceTags = ChoiceTags;
`

Would do the trick (as in many other components) 

Thanks

**Comment by claudia-romano** [comment]
Updated it:
https://codyhouse.co/ds/components/app/choice-tags

Cheers!
